### PR TITLE
Fix link to motivations and goals

### PR DESCRIPTION
**Pull request by jasonkuhrt**
The current README has a broken link. I'm not sure this is the right fix though.

### CODE REVIEW

**Comment by owickstrom** [comment]
Yes, it's correct. Just published the new oden-lang.org and some URLs have changed. Thank you, Jason!

**Comment by jasonkuhrt** [comment]
My pleasure. I would like to see more information about the type system and how much of Haskell is going to come through or not come through or be just plain different. You mentioned somewhere some of the influences but a deeper dive into said influences would be exciting to read once you've had time to write it down.

**Comment by jasonkuhrt** [comment]
I have no idea but maybe [Liquid Haskell](https://github.com/ucsd-progsys/liquidhaskell) ([introduction](http://ucsd-progsys.github.io/liquidhaskell-tutorial/), [demo](http://goto.ucsd.edu:8090/index.html)) is of interest to you/Oden. Anyways, enough off-topic here : )

**Comment by owickstrom** [comment]
Yeah, probably gonna write more stuff in the blog this spring about the progress. However, getting close to Haskell takes a long time and I want to focus on getting Oden up to the level that one can write useful programs interfacing with Go libraries, basically a polymorphic Go with s-expressions. Then it's probably time to add more powerful features. Thanks for the feedback!

**Pull request merged**
