### PR TITLE
Environment, dot operator

### PR DESCRIPTION
**Pull request by owickstrom**
This is a biggie. The old `Identifier = Unqualified | Qualified` is replaced with a simpler Identifier and the dot operator (member access) is introduced for expressions like `foo.bar.baz`. The inferencer decides what kind of access it is, struct field or package member.

```haskell
data Expr t = ...
            | StructFieldAccess SourceInfo (Expr t) Identifier t
            | PackageMemberAccess SourceInfo Identifier Identifier t
```

The Environment construct is also refined, allowing for a much simpler handling of environments in the `Build.hs` module. The `Package` constructor in Core is richer, now containing the parameterized import type. The following type signature shows how *ImportReferences* are resolved into *ImportPackages*.

```haskell
resolveImports :: Importer
               -> Untyped.Package [Untyped.ImportReference]
               -> IO (Either PackageImportError (Untyped.Package [Core.ImportedPackage], [UnsupportedTypesWarning]))
```

An imported package is the import alias along with the complete imported `Package` value.

```haskell
data ImportedPackage = ImportedPackage SourceInfo Identifier Package
                     deriving (Show, Eq, Ord)
```

Then an untyped package with resolved imports gets inferred and you get a typed package:

```haskell
inferPackage :: Untyped.Package [Core.ImportedPackage]
             -> Either TypeError Core.Package
```

I have not implemented tuple member access and support for polymorphic fields in structs. I think that the change so far is very big and as soon as possible I want to cut this out into a PR. Then I can do those two remaining features.

There's also one case that the parser cannot handle right now, but I'll put it into another issue.

### CODE REVIEW

**Comment by AlbinTheander** [comment]
If I want to test this PR, which case can't the parser handle right now? :-)

**Comment by owickstrom** [comment]
Accessing a struct field on the result of applying a function: `foo(y).Bar`

**Comment by AlbinTheander** [comment]
This doesn't seem to work for structs with more than one field. This doesn't compile, but if you remove the `y` field, it works perfectly:

```
package main

import fmt

type Point = { x int, y int }

p = Point{3,5}

main() = fmt.Println(p.x)
```

**Comment by owickstrom** [comment]
Right, that is because we don't have records yet and the fact that when inferring `p.x` the inferencer also infers `p` to be a struct with a single field `x`, and nothing more. That struct with a single field cannot be unified with a struct with both `x` and `y`, i.e. `Point` in your example.

As Go won't accept a struct `{x int, y int}` where it expects `{ x int }` we can't simply let those types unify in Oden and be done with it. We need to instantiate each function taking a struct (or record if you will) with the rows that are actually used.

I think we discussed this earlier, and that it's what we want to do in the long run. Do you think we can live with this very limiting behaviour for now? :)

**Comment by AlbinTheander** [comment]
I think we can live with that.

Some smoke testing didn't reveal anything strange and I think the code looks good, but I have to admit that I haven't had the time to really get into the details.

I say merge it! :-)

**Pull request merged**
